# Generated by Django 5.0.4 on 2024-05-04 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StreetLeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=20, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=20, unique=True, verbose_name='Apellido')),
                ('street', models.TextField(verbose_name='Calle')),
                ('phone', models.CharField(max_length=20, unique=True, verbose_name='Telefono')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo')),
                ('photo', models.ImageField(upload_to='foto', verbose_name='Foto')),
                ('facebook', models.URLField(verbose_name='Facebook')),
            ],
            options={
                'verbose_name': 'Lider de calle',
                'verbose_name_plural': 'Lideres de calle',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200, verbose_name='Titulo')),
                ('description', models.TextField(verbose_name='Descripcion')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo')),
                ('photo', models.ImageField(upload_to='foto', verbose_name='Foto')),
                ('slug', models.SlugField(editable=False, max_length=300)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.streetleader')),
            ],
            options={
                'verbose_name': 'Lider de calle',
                'verbose_name_plural': 'Lideres de calle',
            },
        ),
    ]
