# Generated by Django 5.0.4 on 2024-05-04 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_contact_alter_news_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='message',
            field=models.TextField(blank=True, verbose_name='Mensaje'),
        ),
    ]
