# Generated by Django 5.0.4 on 2024-05-11 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_attachment_options_attachment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='photo',
            field=models.ImageField(upload_to='attachment', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='street',
            field=models.TextField(max_length=255, verbose_name='Calle o Direccion'),
        ),
        migrations.AlterField(
            model_name='news',
            name='photo',
            field=models.ImageField(upload_to='news', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='streetleader',
            name='photo',
            field=models.ImageField(upload_to='leader', verbose_name='Foto'),
        ),
    ]
